config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'recipes#index'
  resources :recipes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredents.rb
class Ingredents < ApplicationRecord


end

app/models/instructions.rb
class Instructions < ApplicationRecord

end

app/models/recipe.rb
class Recipe < ApplicationRecord
     validates :title, presence: true
     has_one_attached :recipe_image
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

app/models/users.rb
class Users < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Clearance::Controller
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    def index
        @recipes = Recipe.all
    end
    def show
        @recipe = Recipe.find(params[:id])
    end

    def new
        @recipe = Recipe.new
    end

    def create
        @recipe = Recipe.new(recipe_params)
        if @recipe.save
          redirect_to recipes_path(@recipe)
        else
          render :new
        end
    end
 
    def edit
        @recipe = Recipe.find(params[:id])
    end

    def update
        @recipe = Recipe.find(params[:id])
        if @recipe.update(recipe_params)
          redirect_to edit_recipe_path(@recipe)
        else
          render :edit
        end
    end

    def destroy
        @recipe = Recipe.find(params[:id])
        @recipe.destroy
        redirect_to recipe_path
    end

    private

    def recipe_params
        params.require(:recipe).permit(:title, :recipe_image,:ingredients, :body)
    end

    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/Ingredents/index.html.erb
<table class="table">
<tbody>
  <% @ingredents.each do |ingredent| %>
    <tr>
      <th scope="row"><%= ingredent.name %></th>
      <td style="colour: <%= transaction.category.colour %>"><%= ingredent.category.name %></td>
      <td>
        <div class="float-right">
          <%= link_to 'RecipeDescription', ingredent_path(ingredent), { class: 'btn btn-primary btn-sm' } %>
          </div>
      </td>
    </tr>
  <% end %>
</tbody>
</table>

app/views/Ingredents/show.html.erb
# <div class="row">
#   <div class="col col-sm-12">
#     <%= link_to transactions_path, { class: 'btn btn-sm btn-primary'} do %>
#       <i class="fa fa-chevron-left"></i> Back
#     <% end %>
#   </div>
# </div>

# <hr>

# <div class="row">
#   <div class="col">
#   <strong><%= @recipe.title %></strong>
#   </div>
  
# </div>

# <div class="row">
#   <div class="col">
#   Ingredients: <strong><%= @Ingredient.name %></strong>
#   </div>
#   <div class="col">
#   Ingredients: <strong><%= @Ingredient.quantity %></strong>
#   </div>

#   <div class="col">
#     Instructions: <strong><%= @Instruction.body %></strong>
#   </div>
 
# </div>

app/views/contacts/index.html.erb
# <table class="table">
# <tbody>
#   <% @contacts.each do |contact| %>
#     <tr>
#       <th scope="row"><%= transaction.name %></th>
#       <td style="colour: <%= transaction.category.colour %>"><%= transaction.category.name %></td>
#       <td>
#         <div class="float-right">
#           <%= link_to 'Details', transaction_path(transaction), { class: 'btn btn-primary btn-sm' } %>
#           <%= link_to 'Edit', edit_transaction_path(transaction), { class: 'btn btn-primary btn-sm' } %>
#         </div>
#       </td>
#     </tr>
#   <% end %>
# </tbody>
# </table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kanchan Kitchen</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <%= link_to 'Kanchan Kitchen', root_path, { class: 'navbar-brand' } %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item ">
            <a class="nav-link " data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Recipes</a>
            <div class="nav-item">
               <%= link_to 'All', recipes_path, { class: 'dropdown-item' } %>
               
               <%= link_to 'New', new_recipe_path, { class: 'dropdown-item' } %>
                
            </div>
          </li>
        </ul>

        <div class="my-2 my-lg-0">
          <div class="nav-item text-light">
            <% if signed_in? %>
              Hello <%= current_user.email %>
              <%= link_to 'Sign out', sign_out_path, method: :delete, class: 'btn btn-primary' %>
            <% else %>
              <%= link_to 'Sign in', sign_in_path, class: 'btn btn-primary' %>
            <% end %>
          </div>
        </div>
      </div>
    </nav>

    <br>

    <div class="container">

      <div id="flash">
        <% flash.each do |key, value| %>
          <div class="alert alert-danger" role="alert">
            <%= value %>
          </div>
        <% end %>
      </div>

      <%= yield %>
    </div>

  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>

    <% if @recipe.errors.any? %>
      <% @recipe.errors.full_messages.each do |message| %>
        <div class="alert alert-danger" role="alert">
          <%= message %>
        </div>
      <% end %>
    <% end %>

<div class="form-group row">
    <div class="col-sm-2">
      <%= f.label :title, { class: 'col-form-label' } %>
    </div>

    <div class="col-sm-10">
      <%= f.text_field :title, { class: 'form-control' } %>
    </div>
</div>


<div class="form-group row">
  <div class="col-sm-2">
     <%= f.label :ingredients, { class: 'col-form-label' } %>
  </div>

  <div class="col-sm-10">
     <%= f.text_field :ingredients, { class: 'form-control' } %>
  </div>
</div>


<div class="form-group row">
   <div class="col-sm-2">
      <%= f.label :body, { class: 'col-form-label' } %>
   </div>

   <div class="col-sm-10">
      <%= f.text_field :body, { class: 'form-control' } %>
   </div>
</div>

<div class="form-group row">
  <div class="col-sm-2">
     <%= f.label :recipe_image, { class: 'col-form-label' } %>
  </div>

  <div class="col-sm-10">
     <%= f.file_field :recipe_image, { class: 'form-control-file' }  %>
     <% if @recipe.recipe_image.attached? %>
        <hr/>
        <%= image_tag @recipe.recipe_image.variant(resize: "400x400") %>
     <% end %>
  </div>
</div>

<div class="form-group row">
    <div class="col-sm-12">
      <%= f.submit class: 'btn btn-primary float-right' %>
    </div>
</div>
<% end %>

app/views/recipes/edit.html.erb
<div class="row">
  <div class="col col-sm-12">
    <%= link_to recipes_path, { class: 'btn btn-sm btn-primary'} do %>
      <i class="fa fa-chevron-left"></i> Back
    <% end %>

    <div class="float-right">
      <%= link_to recipe_path(@ad), { method: :delete, class: 'btn btn-sm btn-primary' } do %>
        <i class="fa fa-trash"></i> Delete
      <% end %>
    </div>
  </div>
</div>

<hr>

<%= render 'form' %>

app/views/recipes/index.html.erb
<div class= "row">
  <% @recipes.each do |recipe| %>
    <div class= "col-sm-4">
    
    <% if recipe.recipe_image.attached? %>
    <hr/>
    <div class="row">
    <div class= "col">
      <%= image_tag recipe.recipe_image.variant(resize: "300*300") %>
      </div>
      </div>
      <% end %>
          <div><%= recipe.title %></div>
          <%= link_to 'RecipeDescription', recipe_path(recipe), { class: 'btn btn-primary btn-sm' } %>
        </div>
  <% end %>
</div>

app/views/recipes/new.html.erb
<div class="row">
  <div class="col col-sm-12">
    <%= link_to recipes_path, { class: 'btn btn-sm btn-primary'} do %>
      <i class="fa fa-chevron-left"></i> Back
    <% end %>
  </div>
</div>

<hr>

<%= render 'form' %>

app/views/recipes/show.html.erb
<div class="row">
  <div class="col col-sm-12">
    <%= link_to recipes_path, { class: 'btn btn-sm btn-primary'} do %>
      <i class="fa fa-chevron-left"></i> Back
    <% end %>
  </div>
</div>

<hr>

<div class="row">
  <div class="col">
  <strong><%= @recipe.title %></strong>
  </div>
</div>

<div class="row">
  <div class="col">
  Ingredients: <strong><%= @recipe.ingredients %></strong>
  </div>
</div>
  
<div class="row">
  <div class="col">
    Instructions: <strong><%= @recipe.body %></strong>
  </div>
</div>
</div>